spring:
  application:
    name: petlife-backend

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=petlifeDB;encrypt=true;trustServerCertificate=true
    username: test
    password: 123

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  web:
    cors:
     allowed-origins: "http://localhost:5173"
     allowed-methods: "GET,POST,PUT,DELETE"
     allowed-headers: "*"
     allow-credentials: true


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # 🔐 Spring Security（先預留，之後一定會用）
  security:
    # 未來 JWT / OAuth2 會用到
    oauth2:
      client:
        # Google / Line Login 會填在這裡
        registration:
          google:
            client-id: your-client-id
            client-secret: your-client-secret
            scope:
              - email
              - profile
      

server:
  port: 8082

# JWT
jwt:
  secret: MySuperSecretKeyForJwtGeneration1234567890
  expiration: 3600000 # 1小時 (毫秒)

