spring:
  application:
    name: petlife-backend

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=petlifeDB;encrypt=true;trustServerCertificate=true
    username: test
    password: 123

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8082

jwt:
  secret: MySuperSecretKeyForJwtGeneration1234567890
  expiration: 3600000

google:
  client-id: 70410001365-t87v8nd57cf2s3qa1mipfpftqsppr3hd.apps.googleusercontent.com
  client-secret: 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
  redirect-uri: http://localhost:5173/login