spring.application.name=backend
server.port=8082
server.servlet.context-path=



jwt.secret=PetLifeProjectVeryLongSecretKeyForSecurityPurposes1234567890!@#


google.client-id=dummy_id_for_startup
google.client-secret=dummy_secret_for_startup
google.redirect-uri=http://localhost:8082/login/oauth2/code/google